FROM node:alpine3.20 AS build

WORKDIR /app

ARG VITE_EMAILJS_SERVICE_ID
ARG VITE_EMAILJS_TEMPLATE_ID
ARG VITE_MUX_VIDEO_URL
ARG VITE_EMAILJS_PUBLICKEY

ENV VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID
ENV VITE_EMAILJS_TEMPLATE_ID=$VITE_EMAILJS_TEMPLATE_ID
ENV VITE_EMAILJS_PUBLICKEY=$VITE_EMAILJS_PUBLICKEY
ENV VITE_MUX_VIDEO_URL=VITE_MUX_VIDEO_URL


COPY package*.json ./

RUN npm ci

COPY ./ ./

RUN npm run build

FROM caddy:alpine

COPY --from=build /app/dist /usr/share/caddy

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
EXPOSE 443

