name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Optional: Enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      # Only run this step when pushing to main branch
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kazabokit:latest
        Optional: Add build arguments if needed
        build-args: |
          VITE_EMAILJS_SERVICE_ID=${{ secrets.ARG1 }}
          VITE_EMAILJS_TEMPLATE_ID=${{ secrets.ARG2 }}
          VITE_EMAILJS_PUBLICKEY=${{ secrets.ARG2 }}
        cache-from: type=gha
        cache-to: type=gha,mode=max